vic-net-sk: ENC[AES256_GCM,data:OcPWIWzuSLO4HXXaJMIUXGryOwiZFuI+NMxaF6BZaTiboxmgETYv/Af55Q4=,iv:Ovz+0Ori3aZnyNviuoaOSZvK3eE6CZS/C7OU7gjHVH4=,tag:C5/XpCRIf1Guj+7CWprsqA==,type:str]
sops:
    age:
        - recipient: age1fyvl0aynevv74jvtdxklhzyx3yqj54h5kr93sqlsxc4yqp2gzd6qlqwwu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOG5vL3RtZkw1bnJSQ3BS
            VnlVY0NlVEJvRVhYY0dyenIzOXM5VFllNVNVCmplaTBuT1ZKbHN5R1NKdnJKQWN2
            L09zemhlZ3psWno1MDhLOVo3WGU1aE0KLS0tIGZjbVoydXFieG1oOEt0aWNzVHZY
            ck9vdUhmWjZ6VW81ZDlnb0dDNjZNZ1kKfnbg0kpolGzpE9gKW58bbkxcj61VdWhc
            C+ZPXxU0xBhbk1rWHfhfiy2scuZLFE3rowDr1TWIAHqUTP29LKnetQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12x9pzkvjh3re8laaq52a3ms297n9n87zf0lshrujrr83jnqclepq6xhqkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeVM2NkZTbjdCM0IrOER0
            dEtIVVlvS0J3eU9vNlRTWUhUeG1NRkU5d1JFCi94aEhvTEdVRUw2c0RBNjRqMlR3
            THNqYzB5YVl5MFVpZ3FGSjNmN1FWUjgKLS0tIEo5WWtPaGhDYWdScVBuTGlVVnZy
            dzdTZTA4KzdwOG92YW1yQWc0SFMycTgKDcMZDicLdAfQmLoJyj3sW08BjimwOnST
            jOVYnkCNANpnbVUtZcqH9Xu2k7ID9Uw8hrosBgPiq0BWQEt63mJQhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T23:36:16Z"
    mac: ENC[AES256_GCM,data:BnMTwDU+9MJQYvxCgd50bLcZ3JW1VdJxlLk735BxjQK2+nI33q9WCWd8fxeHWof8PItPralYmzjz0MPXIc/aRk6Rcf4Y2mEEopdQzPvKbuIB7GbzeTSYo4vZJC1KoXMaOK1RzKxFO68U/Y5mqSLluZSyNmiCq3EU7Vm75cg6fuA=,iv:D4CopxrDUhLXmE+vwzyxKQEUvjxH/ij/s65AusHUPaM=,tag:ahXE/TnWBcEhrRUia4jnZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
