forgejo-runner-token: ENC[AES256_GCM,data:CBZ/ybpp50dpQzAf5U5ZmXbh0VnUblO1MoedN6XQkqy8EagT5co5dKgLZnOp5Q==,iv:WxPwM+qMGfQn7cs0y8js6uQY5KmrWmGj3l6FhJnN3lo=,tag:B6847/Llche7HoH21hU3/g==,type:str]
vic-net-sk: ENC[AES256_GCM,data:aNoglSXVhgcPZ9h8bmA8t9Xux1vpIu458q4dV+y7+ydzRxgneHTGhMW8Zjo=,iv:nMBpK7P+PAIMqs7RlKRV57y5NEbRb6FScky5h9a4Ulk=,tag:1iCDI8Qb8udv5EhAzoTjAQ==,type:str]
sops:
    age:
        - recipient: age1fyvl0aynevv74jvtdxklhzyx3yqj54h5kr93sqlsxc4yqp2gzd6qlqwwu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTQ1NHo3MlpCUTNtMVBv
            bUtkZnV2amxNbDd4dHR3d1NEY1BRQUh4QWdZCnNFRWpwVlVlU2xoVEFQa01GQXRv
            N1FtbkVpWkhDQThtZWdwS3B4NEFNSzQKLS0tIENRbHZSNWoxeEtjSUFPbG04VWt3
            OGFkVzJuTk9GVUxVaW1xeGY0NHpocTAKuhG43xEFa6bQycWopcMZP/+E6VGViBId
            4PkbdrHzyZZzUu1q/keqZuMG1KfyL+kOfsj9tcyfZ/zWP5vUnGFqyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nay99fvluh7fg2xgw7p0ks6fupg0p63uysvscua9uhsa46zqu43shuh0sk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONDhVaTJXQlh0dVRheEJo
            SGQrb3RuTDVCeHR3MzIrYlV4b3Q0alB3N0FjCnZndkIwb2l4Zkl3MU5Qdjc4cVE1
            TDU1Qld4K2VZa0hPQjR6MnlSUGpSR0EKLS0tIExCRDUxekVuRUVZVmNGT1FMYy9n
            cDFMaVdMNFBqclE0V3Z6TWNpNE5LcUkK+JkWqC0A5W/vmw2suti9ARnGPahd+kUq
            DY++Arzq/Lh2ryHgZ90gfW3BoyaouNsUVz4NMZmHwXxUBLJfgaavjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T15:07:26Z"
    mac: ENC[AES256_GCM,data:WsSe3KxCMO/Y5vj9+QzLWmk28x7SqaSINvbFRIayMz1evm5+81Zk/Eu4zLgH3uUf//lvTD3/shNUHH3eZFDwglaNwSCXBVqErZ6M0Vg2g534/nKhBo8LzcJmXxCxeLITK3ULbetJ6hLjtLn2XIGblBR1AqkCyv0snkcuntD8GgA=,iv:fUxUtn1Gs5+0fZPNcb+17SK+HgsCiU/944tbOXoU7OI=,tag:pTjVwBv10ElI2X5+55yo7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
