forgejo-runner-token: ENC[AES256_GCM,data:AMtswOhsBierxkQFvg85HkiJSN9v6ZXwqYCR9miSwge97iKJUnMwZA==,iv:3R/2Yr2Q7sfNvqKyr1aDe+I0J8qaAx9ML7HrpkQuPD0=,tag:g+TAwjrIsnNuRinsLOOtdA==,type:str]
vic-net-sk: ENC[AES256_GCM,data:aNoglSXVhgcPZ9h8bmA8t9Xux1vpIu458q4dV+y7+ydzRxgneHTGhMW8Zjo=,iv:nMBpK7P+PAIMqs7RlKRV57y5NEbRb6FScky5h9a4Ulk=,tag:1iCDI8Qb8udv5EhAzoTjAQ==,type:str]
sops:
    age:
        - recipient: age1fyvl0aynevv74jvtdxklhzyx3yqj54h5kr93sqlsxc4yqp2gzd6qlqwwu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTQ1NHo3MlpCUTNtMVBv
            bUtkZnV2amxNbDd4dHR3d1NEY1BRQUh4QWdZCnNFRWpwVlVlU2xoVEFQa01GQXRv
            N1FtbkVpWkhDQThtZWdwS3B4NEFNSzQKLS0tIENRbHZSNWoxeEtjSUFPbG04VWt3
            OGFkVzJuTk9GVUxVaW1xeGY0NHpocTAKuhG43xEFa6bQycWopcMZP/+E6VGViBId
            4PkbdrHzyZZzUu1q/keqZuMG1KfyL+kOfsj9tcyfZ/zWP5vUnGFqyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nay99fvluh7fg2xgw7p0ks6fupg0p63uysvscua9uhsa46zqu43shuh0sk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONDhVaTJXQlh0dVRheEJo
            SGQrb3RuTDVCeHR3MzIrYlV4b3Q0alB3N0FjCnZndkIwb2l4Zkl3MU5Qdjc4cVE1
            TDU1Qld4K2VZa0hPQjR6MnlSUGpSR0EKLS0tIExCRDUxekVuRUVZVmNGT1FMYy9n
            cDFMaVdMNFBqclE0V3Z6TWNpNE5LcUkK+JkWqC0A5W/vmw2suti9ARnGPahd+kUq
            DY++Arzq/Lh2ryHgZ90gfW3BoyaouNsUVz4NMZmHwXxUBLJfgaavjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:57:52Z"
    mac: ENC[AES256_GCM,data:QFm+sOK7mHqyZcSYdsrOdLQOh8JoJRGTXMID+7Q+M1vYJ2rOds5xF64/YzPYQagT53XIFrS+dOFCwA4c8PkDU5NnKo4YR5SgtDGCKhYb9UAJ3uqrddQrN7mfxEj8WFmdgV8C1HD1AlWLRDaTpY1OWNP2Syd4peAKpY/FBNRKx7Q=,iv:/eJwnvgAqbwTj16stCvZJtt9DJB6x3KuNfUu88zL2sw=,tag:Gp2Qc7v1UFHoXzCdA1/Zmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
