akos-ipv6-pk: ENC[AES256_GCM,data:UJPE/ktj2EDRCruqKrLu0zgMQmz3ee0dK/UI4cKzqi5GGihUCXO5knCvS6c=,iv:ru9i5Tun/DKBYbgGmbliaqsWRj9dg5fvxSocAv6kohE=,tag:LPnpFG5vbLSRfRKv72nMZA==,type:str]
vic-wg-pk: ENC[AES256_GCM,data:8/kq8cfw7wmA8vBaeDqN0ePs1Tr5c6xjxr4mXeAlDMu/iwze71v9F8mjiD4=,iv:w0hvearQUuBPICZCtLA36xlM/yhYVTKApl2Cm1AIS/Y=,tag:SmOntVONgvZUC9Tg4ShyWw==,type:str]
cf-creds: ENC[AES256_GCM,data:fbc6g1JVD1ESkO3EPxMSyCmywn9h5WrWierk+7TuSR+jnoFdMEe0GErzwufTQP2g+FRiYVnPDWjLIFbpBdY209IaFcEbs6J/guDXWaNayBS3/LRqzY2NIc3F637G,iv:HlBoXLPqVaWYyex7VoYeOD1MMTW9afv8sTVDNoAyVv4=,tag:nn+vIc8TvLd1+ciYQpu3HA==,type:str]
cloudflared: ENC[AES256_GCM,data:p13VKB5/ak5kBouNnitQPBo2XBOKDWks6SWsLSG/NpF9btOPFlgGlAM4WfLshqYjGFrp1oMRxgEO+jSwJYRzw8+Oe6MlvtU7rHQZZrR8ay5UIjhS768Yt0oz5PA22+qoj2aQ88qPCQ3DyphhGaIdf9QQo8ysu/gz8E5K4mrQMNVvsR456rsdOT1XBDWQGNZ3h7g2RtEgZ2OTVl+pyL3HBhLCucbJzW6u6gX11/Plv/RdJZkYtfD1DxHLWPYuO52vjvmAQZmQskkLmd35qtMX6MvHhoaujBDd5GoAnxsvB0G5d/ejIr0PXw==,iv:ElkEV2KhROmDrkmmaWbAl1CspZQ5co0YXVmT7Dda6ss=,tag:gW9kGekrW4t9UXVaIeIUfg==,type:str]
sops:
    age:
        - recipient: age1fyvl0aynevv74jvtdxklhzyx3yqj54h5kr93sqlsxc4yqp2gzd6qlqwwu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQVBZUmhlSU5waXZnUFRM
            RHlOQlBxM1VraVhaaVBIOXJQRWhMR2hkUldRCnVoUzNpN2I2aVY4clQwY3RMeGRB
            eS9ZNDdMdUM3eWFpbmNEWVV1cFY4T2cKLS0tIDZpSitsNEhreHh3Zks5dFc1dnhv
            aVI0WE1lQldqbXFRQkdZall3MW9ubncKtPApB3qizZ0KMFveSQsjbBa6fdTP57sS
            hybEV+j/Xv+MzLHTqT533VHsRa7BrO6mgcARJYJwFD6A+F3yrQMK8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10xf6lqcxjr0xmepfsymvyeppu3m922zrtf2x63aqkwgvqwjj7ymqs404cm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bjIzY2dXMEdjV0dqY2h6
            bm9BQXpWeVU0clk0Y1NKSmE2MnE1ek9yYkI0Ckdrdm54ZEZKWXFGMkJMZWRzM0Fj
            a2l5NVR1S3o3Y3hTa3VUeWd4VVVhZ2MKLS0tIGNtMnlBcVFQL1M0dER6WjdlMFRu
            WmFFblZjczlwVzhNNk1ORTlralVCWnMK9/0ZKhkvMBezoK93tLU7EadOurC74r9g
            +xQydu1tmmmiML6UrlPbC9wM+6jDgS+rXnACG8irk8/iH8sfnowmfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T19:26:42Z"
    mac: ENC[AES256_GCM,data:ULG1xRxAWDdck0SSFTgwPajrZmHY/h8UzZOH0IWabirG0XQNJJDSuig1yuJls6aGW8Z6G8pcHU2i3ax9ujIEVmMbhMSBkuh4RGsMOsuqM4JZgYVhSdlai0SsafntGgxG8lZNrSE/dMqLhi3hOGkDY58StaPAx5nx1/woR7OKtRw=,iv:9rzD0lLl+aIqerkZFX63yiWf4/Td/3x3BwQUG/Hh8gQ=,tag:mywg5w+YGu3wdF4AQR3HOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
