cloudflared:
    2e679b98-a35a-4c13-84f1-b9296bc55bb2: ENC[AES256_GCM,data:D+3U2lZi51Ewviie09GJk4cmLq4BME0n9zcweoPMU8LFn2HesF2mZkIdKdoR6ECYWSwowlYiX5u6UIakHqn15WjkcCFIy2T/SpbmLGjRl5khB09A3xWdCTbD9firXy0cBwwCfS3pMsW9jk3eec+TNMWQY2xRa1sXXmijzqOJXTv1xCaNjdNqeKkNTIZu1qXdaRRlx1O7omA9hpgjvRuQCio=,iv:oiHXd/yo5j7bDx+31erkh+n4huvk4S8nnITHlDOnikg=,tag:bioKmBq4DPqUM5JHnh+VFg==,type:str]
    90d18543-7a60-47d1-805f-ec1ee80ea962: ENC[AES256_GCM,data:dUwORy5OjmdswA2KWYbQ7pYIpUcU0gzsrQkffthPEN2e6E2WthNoguERUTkhB5/g6l29tTs4gH3L1TmzOrdpOsMn1DRSpFOGcKSeNJXcRisU8NhKufuBfjrAFO8eHKfB+uM9RrXPRKwTX+BwnyulAe0wU7HINogrC4nB/5cglojiZSEgH7TcCuG33Xt4mhF2FXaxI6ZAR9NifAJEHOSE5K4=,iv:zawgwO+x6jtXI9AIDB/VO0jjcJ4bEUXRhWCWh9m0epU=,tag:7BIuG0bShHVs8Yp87ZF4zw==,type:str]
plausible:
    secretKeybase: ENC[AES256_GCM,data:btA2zJF+k2/oakeTWx2qzEUv6CaW644hjLRwlxrCQlu8wtfboqMZ8eV3KsFw1ugCs4FpADiKAw2ajvTuiWdVFPver4p3JwcKs9VGCOuO6QiqisNo+jb0xQ==,iv:9CRflMACWR+b9p4xhglDxwbhq19ksNjHmMrELv2JiHg=,tag:EnrJqyy5kslSkbX29t/irw==,type:str]
transmission: ENC[AES256_GCM,data:yjV++NGNt17Xv9JSUIn2WeijCiKxr8lac0pmVu5E6H/fBeav6Huo7uM/WKW0I6DJS7/VcP54anWns4kdVrcmvd0aY54JvmIDfvrwrXYQcpZGD8zEkR4RDb0MkTSsJQsEhNxoTj95RQ==,iv:MniOJVKr3F6pcJLQsnmGKz6Eb4MgefoJXog+dmVAEy0=,tag:pjvzIC4/6e6/Cx7KheAcSg==,type:str]
transmissionWebhook: ENC[AES256_GCM,data:ZIdngsBM675hfg/wBHUKuVRyBGHLLYDUo39ukXK1WnvXEhYi9CRsWhve8IlyQxtx6eFZQmVEqqrtyk6+cBUpS6u8NnBhi4NuH5zC9kzaVdH8Qs/txQMt0QrQuUEx/3e7L+Wm/hLnWRgA8SactxQLfsQwPlXC/G0yZA==,iv:2PlSs/PxdQRlPz9nDqpFz0VHGMYnSL9VLXr9PaBIro8=,tag:OYxRsyrJ0BR0iblrETlB2Q==,type:str]
altweb-wg-sk: ENC[AES256_GCM,data:J6FBd+QnNEZS13R2v1gfIdr99g5f85ZKlNvWWbaiQofH2YxQM4fu2rYiwDA=,iv:RympyWrQ8RKfaShy7MYBXWzZPBzm3/3Zs6oIs6747f0=,tag:xUj7wjYV9lGT5j0oHOeU0Q==,type:str]
sops:
    age:
        - recipient: age1fyvl0aynevv74jvtdxklhzyx3yqj54h5kr93sqlsxc4yqp2gzd6qlqwwu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTk9HWkZGQTVPT1RWaHFm
            RTdEQUhkNVZIbnlsVkpSYUUrY1djRVpwVGwwCmZUWjhHOUN2VlM3bkc4U1puc1pU
            bVpOTzg5Ly9GMnhmbTNUbjlmWjFuQ0EKLS0tIFBYdyt1NlJ4UDlta0NrTXdxVEFW
            YWNEaXphWWRsY1ppQi9rcGdpU0RJQ3MKpN3PqBrK6950yakFWAl3ZP//rnyx68nl
            sEHUyPetvGsR9jWh/5R0pYSPf2QpwIrYfOBUBaHLPNBpoL2gEtEbBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age108c25algyks6pa5z9asa7dzxfs4j23qwwhzfygvlty9lkverecyqpmj27g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbDg2UHlVNTMvcjdEWVhw
            Qmg1VTgyeWUrcTVXbVljL1ozVEtmZjZrSG1nCnZDRXpOQmZLT0tRRm5mYjVyWlA5
            ZGdUUDRHd3kyVnBNNy9OVHNBYlpOTDAKLS0tIGY1QjRXVVRrOHF0aDhCYXlnVitz
            ZGdZMVVxOFpJc1AvS1h1VG1Gd0luSnMK4fJNIQ/wQUuQdzRheCLG/x6UH2c7SY3A
            IYGmEK7cPhT/8pPIWAOYU67gdBsfeFaRRmHolct9ZQGUQfkIeml/tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T15:57:21Z"
    mac: ENC[AES256_GCM,data:iHlxXvGM/8OIdCL1dzgVaQDUAbeVH/bwDkSxGe8RZmI4rSaFsYtYZBdYeapp0pu9izP/1NTVDBzv7Qt3vwLxF4d2w8aXUpHzSfIVN4ubFDJQIc4YYAPOFBs3HCj9lJwVqVKIubGG+EPmTdTV8fzMIwC3a1PXrzksErFrFhlV3BI=,iv:YmVTY9BpAXAbE+ascklfndbCjPJH7QKrGJKcpL6fEVc=,tag:+9lpeGieSYpjiJjfHupaiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
